apiVersion: v2
actions:
  - name: "Execute pod restart"
    events:
      - name: "sh.keptn.event.action.triggered"
        jsonpath:
          property: "$.data.action.action"
          match: "restart"
    tasks:
      - name: "Restart pod"
        image: bitnami/kubectl:1.21
        workingDir: "/bin"
        cmd:
          - bash
          - '-c'
          - kubectl delete pods -l app=$(SERVICE) -n $(PROJECT)-$(STAGE)
        env:
          - name: PROJECT
            value: "$.data.project"
            valueFrom: event
          - name: STAGE
            value: "$.data.stage"
            valueFrom: event
          - name: SERVICE
            value: "$.data.service"
            valueFrom: event
      - name: "Show Pod"
        image: bitnami/kubectl:1.21
        workingDir: "/bin"
        cmd:
          - bash
          - '-c'
          - kubectl get pods -n $(PROJECT)-$(STAGE)
        env:
          - name: PROJECT
            value: "$.data.project"
            valueFrom: event
          - name: STAGE
            value: "$.data.stage"
            valueFrom: event
          - name: SERVICE
            value: "$.data.service"
            valueFrom: event
